application:
  # dev开发环境 test测试环境 prod线上环境
  mode: dev
  # 服务器ip，默认使用 0.0.0.0
  host: 0.0.0.0
  # 服务名称
  name: wangStoreServer
  # 端口号
  port: 9090
jwt:
  # token 密钥，生产环境时及的修改
  secret: wang-store-server
  # token 过期时间 单位：秒
  timeout: 86400
database:
  # 数据库类型 mysql, sqlite3, postgres, sqlserver
  driver: mysql
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  dbName: wangstore
  ParseTime: true
  timeout: 1000ms
  loc: Local

#  conn: root:123456@tcp(127.0.0.1:3306)/wangstore?charset=utf8&parseTime=True&loc=Local&timeout=1000ms